### ISSUE TITLE
Visual evaluation of the model

### ISSUE THREAD

**Issue by isaeldoori** [zanilzanzan/FuseNet_PyTorch#12]
Hi,

I want to thank you for the work you have done, it has helped me a lot for my Machine Vision course. I have everything working on both the NYUv2 and SUN RGB-D datasets, I even have the model working on a different dataset. However, I was wondering how you made the plots of the visual evaluation of the FuseNet model?
![fusenet_visual_evaluation](https://user-images.githubusercontent.com/7880827/47421958-f373b680-d781-11e8-87cf-6296a9514e08.PNG)

Just like this one in your paper.

Thanks in advance!

**Comment by hazirbas** [comment]
Hey,
if you have a tensor of [numCls, H, W], you can take the max and put palette using PIL.Image:
```python
with open('pascal_voc_colormap.txt', 'r') as f:
    palette = numpy.array([[int(x) for x in line.split()] for line in f]).flatten().tolist()
im = Image.fromarray( (numpy.argmax( result , axis = 0).astype( numpy.uint8 ) ) )
im.putpalette(palette)
im.save('filename.png')
```
[pascal_voc_colormap.txt](https://github.com/zanilzanzan/FuseNet_PyTorch/files/2510574/pascal_voc_colormap.txt)
