### ISSUE TITLE
hdf5 train test file

### ISSUE THREAD

**Issue by hzwangjl** [zanilzanzan/FuseNet_PyTorch#14]
could you share the script file to create the nyu_class_10_db.h5?  thank you so mush~

**Comment by zhuhui100** [comment]
hello, I found I can't  download   nyu_class_10_db.h5  file. so, How to Download it?

**Comment by hazirbas** [comment]
I am able to download it [here](https://vision.in.tum.de/webarchive/hazirbas/fusenet-pytorch/nyu/nyu_class_10_db.h5)
