### ISSUE TITLE
mapping 894 to 40

### ISSUE THREAD

**Issue by NanWangAC** [zanilzanzan/FuseNet_PyTorch#15]
hello, I have a question sbout how can I map data sets from 894 classes to 40 classes. Looking forward to your reply. thank u!

**Comment by zanilzanzan** [comment]
Which dataset are you talking about?

**Comment by NanWangAC** [comment]
the nyudv2，how can I map data sets from 894 classes to 40 classes？thank u!

**Comment by zanilzanzan** [comment]
Ok, I found the object-class mapping (from 894 classes to 40) on [this repository](https://github.com/shelhamer/fcn.berkeleyvision.org/tree/master/data/nyud). So, if you download the the [data](http://dl.caffe.berkeleyvision.org/nyud.tar.gz) there, the class and mapping information is included in the package as a .mat file. I wanted to make it easier for you, so I created this [.json file](https://drive.google.com/file/d/1fkuRcKkQDbyL1C1hEwNtQ3FYoh9mfmHP/view?usp=sharing). The keys are the class IDs of the 894 version, and the values contain the 40-class IDs and names. It is pretty self-explanatory. You can open it up with Firefox to visualize better. Good luck!
