### ISSUE TITLE
Hi! how could i use the aug_util.py to complete data augmentation？

### ISSUE THREAD

**Issue by NanWangAC** [zanilzanzan/FuseNet_PyTorch#17]
Hi! i want to hnow that how could i use the aug_util.py to complete data augmentation？looking forward to your reply. thank u!

**Comment by zanilzanzan** [comment]
What do you mean by "aug_util.py"? There is no such file in the project.

**Comment by NanWangAC** [comment]
oh~, i am sorry to bother u, i make a mistake! very sorry for that

**Comment by zanilzanzan** [comment]
No worries. Hope whatever you are working on worked out. :)
