### ISSUE TITLE
semantic segmentation results on NYU V2 dataset can not be download

### ISSUE THREAD

**Issue by RedJupid** [zanilzanzan/FuseNet_PyTorch#18]
the website of https://goo.gl/hcUFMy is inaccessible

**Comment by zanilzanzan** [comment]
I can still access the link and see file download option. What is the exact error you get?

**Comment by zanilzanzan** [comment]
@RedJupid, can you give me a feedback on this? I’ll close the issue accordingly.

**Comment by zeng32** [comment]
Hi,
I can not download the NYU-Depth V2 dataset from the link " train + test set".
Would you please fix it?

**Comment by zanilzanzan** [comment]
@hazirbas can you check out if the dataset is still accessible please? Looks like the link doesn't work.

**Comment by zanilzanzan** [comment]
@RedJupid, @zeng32, both links are activated. You can download the dataset and the weights now.
