### ISSUE TITLE
RuntimeError when first time run the code

### ISSUE THREAD

**Issue by nessieyang** [zanilzanzan/FuseNet_PyTorch#2]
I just download the dataset of NYU that you put in the same post. And ran the 'Train_FuseNet.py' on Linux. Then it came to the error like this:
![image](https://user-images.githubusercontent.com/38547134/43006957-03750732-8c05-11e8-9d76-ac986ba45bb2.png)

**Comment by hazirbas** [comment]
Hi,
did you solve the issue? I think it happens once you input a 4-D vector instead of 1-D to depth branch.

Best,
Caner

**Comment by hazirbas** [comment]
Please check the issue #1.

**Comment by nessieyang** [comment]
Dear Canel,
Thanks very much! I have solved it!
The problem occurred at line 36, FuseNetClass.py.
The initialization of the first layer have a size mismatch problem. Just use unsqueeze to add a new dimension can solve it.


Best,
Yang 
Research Intern,
Johns Hopkins University 
On 08/07/2018 14:04, Caner wrote:

Closed #2.

**Comment by hazirbas** [comment]
Hi @nessieyang ,
can you please create a merge request?
