### ISSUE TITLE
How do you normalize depth value to fall into 0-255?

### ISSUE THREAD

**Issue by hyclover** [zanilzanzan/FuseNet_PyTorch#21]
I have appreciated your great work. You noted that depth value in NYUDv2 datasets should be normalized. I found that the maximum pixel value of raw depth image is very large(ie, 19576 of 000003.png in dataset) and it has much 0 value. Is it normal? How should I do to normalize it?
Look forward to your reply. Thanks!

**Comment by hazirbas** [comment]
Yes it is normal to have missing depth, encoded with 0. You can divide the numbers by 1000. to convert them to meter.
