### ISSUE TITLE
Per class iou

### ISSUE THREAD

**Issue by Peizhi86** [zanilzanzan/FuseNet_PyTorch#24]
The paper of fusenet has evaluate the classwise IoU scores of 37 classes(table 4).If you have this test code,could you share it with me. #nyuv2 dataset
My email is 1198317677@qq.com
Thank you very much

**Comment by hazirbas** [comment]
Please check [here](https://github.com/MehmetAygun/fusenet-pytorch)

**Comment by Peizhi86** [comment]
Yes,I have tested that github.But it can't solve my problem.I also obey your guidance that submit the result to scannet benchmark,but I even can't register a user.It always show the bug:Failed security question.And I haven't get a reply of the website's personnel.So I want to obtain the test code to calculate per-class-iou of nyuv2.

**Comment by hazirbas** [comment]
For NYU, you can use [this](https://github.com/zanilzanzan/FuseNet_PyTorch/blob/ac277005acfc705c040529ecd8f4a9a99a7e4610/fusenet_solver.py#L141), but for Scannet please consult them directly [here](http://kaldir.vc.in.tum.de/scannet_benchmark/about)

**Comment by Peizhi86** [comment]
Yes,sir.I have read and used that code(for nyu).It can just generate global acc,miou and macc.And it can't generate the per class iou like the table4 of  your paper.
![image](https://user-images.githubusercontent.com/71887308/129843909-9941b324-1349-484f-8176-92e656c20149.png)
Sorry,maybe my problem is too stupid.Please forgive me.
If you don't have the test.py to evaluate per class iou,I won't waste your time any longer.Now I am learing to write it.
If you have the code already written,please share with me.Thank you for your guidance again.

**Comment by hazirbas** [comment]
If you dig into the code, you can actually find that we compute them but only return mean IOU [here](https://github.com/zanilzanzan/FuseNet_PyTorch/blob/ac277005acfc705c040529ecd8f4a9a99a7e4610/utils/utils.py#L41)

**Comment by Peizhi86** [comment]
OK,thank you,sir,I will dig into the principle of miou and that code.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zanilzanzan/FuseNet_PyTorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月18日(星期三) 下午2:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zanilzanzan/FuseNet_PyTorch] Per class iou (#24)





 
If you dig into the code, you can actually find that we compute them but only return mean IOU here
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
